### ISSUE TITLE
recieving CANbus data

### ISSUE THREAD

**Issue by nielser1** [syssi/esphome-virtual-can-bms#5]
Hello syssi,

I am new to the yaml file and my job is to read data from a battery with CAN bus. Now i saw your file and it looked like this is what i needed but i dont know of this is for receiving data or sending data? And if this is for sending CAN data how can i recieve this with ESPHome.
Can you help me?

**Comment by syssi** [comment]
May be this is what you are looking for: https://esphome.io/components/canbus.html

**Comment by nielser1** [comment]
yes, I have already read that 100 times, but I can't figure it out, just attach a normal ID to a CAN ID and add up multiple CAN ID

**Comment by syssi** [comment]
What do you try to achieve? Do you own any specs / definitions about the battery your are trying to talk with? What did you try already and how does the errors look like?
